server:
  port: 8080

spring:
  application:
    name: cloud-provider-8080

  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        group: DEMO
        namespace: public

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tech_interview?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.wyy.tech.entity




payment:
  save1: http://cloud-consumer-8090/payment/save1
  save2: http://cloud-consumer-8090/payment/save2
