server:
  port: 9000

spring:
  application:
    name: cloud-common-user-9000
  main:
    allow-circular-references: true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: public
        group: DEMO
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tech_interview?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.wyy.tech.entity
